Fix missing package
Fixes
```
» echo "{}" | json -p
module.js:471
    throw err;
    ^

Error: Cannot find module 'purepack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/json-explorer-taco/lib/main.js:17:12)
    at Object.<anonymous> (/usr/lib/node_modules/json-explorer-taco/lib/main.js:302:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```